# Tarea 01: Python y NumPy

**Instrucciones:** Completa cada celda de código con tu respuesta. No modifiques las celdas de texto.  
Cada pregunta indica exactamente qué debes escribir.

---
## Parte 1: Python básico

**P1.** Crea una variable llamada `nombre` con tu nombre, y otra llamada `edad` con tu edad.  
Luego imprime el mensaje: `Hola, me llamo Ana y tengo 22 años.` (con tus datos).

In [1]:
nombre = "Johanna"
edad = 35

print(f"Hola, me llamo {nombre} y tengo {edad} años")

Hola, me llamo Johanna y tengo 35 años


**P2.** Dada la lista `numeros = [10, 25, 3, 47, 8, 15]`:  
- Imprime el primer y el último elemento.  
- Imprime los tres primeros elementos usando slicing.  
- Agrega el número `99` al final de la lista.

In [ ]:
numeros = [10, 25, 3, 47, 8, 15]

print("Primer elemento:", numeros[0])       # Primer elemento
print("Último elemento:", numeros[-1])      # Último elemento

print("Tres primeros elementos:", numeros[:3])      # Tres primeros elementos con slicing

numeros.append(99)      # Agrego el número 99 al final de la lista

print("Lista final:", numeros)

Primer elemento: 10
Último elemento: 15
Tres primeros elementos: [10, 25, 3]
Lista final: [10, 25, 3, 47, 8, 15, 99]


**P3.** Dado el diccionario `estudiante` con las llaves `nombre`, `carrera` y `promedio`,  
escribe un `if` que imprima `"Aprobado"` si el promedio es mayor o igual a 6, y `"Reprobado"` si no.

In [ ]:
estudiante = {"nombre": "Carlos", "carrera": "Sistemas", "promedio": 7.5}

if estudiante["promedio"] >= 6:
    print("Aprobado")
else:
    print("Reprobado")

Aprobado


**P4.** Crea una función llamada `calcular_area` que reciba `base` y `altura` y devuelva el área de un triángulo (`base * altura / 2`).  
Llama la función con `base=5` y `altura=8` e imprime el resultado.

In [ ]:
def calcular_area(base, altura):
    return base * altura / 2

area = calcular_area(base=5, altura=8)

print("El área del triángulo es:", area)

El área del triángulo es: 20.0


**P5.** Usa una **list comprehension** para crear una lista con los cuadrados de los números del 1 al 10.  
Imprime la lista resultante.

In [ ]:
cuadrados = [n**2 for n in range(1, 11)]

print(cuadrados)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


---
## Parte 2: NumPy

In [ ]:
import numpy as np

**P6.** Crea los siguientes arreglos e imprime su `shape` y `dtype`:  
- Un arreglo con los valores `[1.5, 2.5, 3.5, 4.5]`  
- Una matriz de ceros de 3 filas × 4 columnas  
- Un arreglo con 6 valores igualmente espaciados entre 0 y 1 (usando `linspace`)

In [8]:

# Arreglo
arr1 = np.array([1.5, 2.5, 3.5, 4.5])
print("Arreglo 1:", arr1)
print("Shape:", arr1.shape)
print("Dtype:", arr1.dtype)
print()

Arreglo 1: [1.5 2.5 3.5 4.5]
Shape: (4,)
Dtype: float64



In [9]:
# Matriz de 3x4
arr2 = np.zeros((3, 4))
print("Matriz de ceros:")
print(arr2)
print("Shape:", arr2.shape)
print("Dtype:", arr2.dtype)
print()

Matriz de ceros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4)
Dtype: float64



In [10]:
# Arreglo con linspace
arr3 = np.linspace(0, 1, 6)
print("Arreglo linspace:", arr3)
print("Shape:", arr3.shape)
print("Dtype:", arr3.dtype)
print()

Arreglo linspace: [0.  0.2 0.4 0.6 0.8 1. ]
Shape: (6,)
Dtype: float64



**P7.** Dado el arreglo `a = np.arange(1, 13)`, usa `reshape` para convertirlo en una matriz de 3 × 4.  
Luego imprime el valor máximo, el valor mínimo y la posición (índice) del máximo.

In [11]:
a = np.arange(1, 13)

matriz = a.reshape(3, 4)

print("Matriz:")
print(matriz)

valor_max = matriz.max()
valor_min = matriz.min()

posicion_max = np.unravel_index(matriz.argmax(), matriz.shape)

print("\nValor máximo:", valor_max)
print("Valor mínimo:", valor_min)
print("Posición del máximo (fila, columna):", posicion_max)


Matriz:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Valor máximo: 12
Valor mínimo: 1
Posición del máximo (fila, columna): (np.int64(2), np.int64(3))


**P8.** Crea dos arreglos de 5 elementos con `np.random.randint` (valores entre 1 y 20).  
Súmalos, réstalos y multiplícalos elemento por elemento. Imprime cada resultado.

In [12]:
a = np.random.randint(1, 21, size=5)
b = np.random.randint(1, 21, size=5)

print("Arreglo a:", a)
print("Arreglo b:", b)

suma = a + b
resta = a - b
multip = a * b

print("\nSuma:", suma)
print("Resta:", resta)
print("Multiplicación:", multip)


Arreglo a: [15  6  3  5  1]
Arreglo b: [11 13 20 15  3]

Suma: [26 19 23 20  4]
Resta: [  4  -7 -17 -10  -2]
Multiplicación: [165  78  60  75   3]


**P9.** Dado el arreglo `notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])`,  
usa **indexación booleana** para obtener solo las notas mayores o iguales a 6. Imprime el resultado.

In [13]:
notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])

notas_aprobadas = notas[notas >= 6]

print("Notas mayores o iguales a 6:", notas_aprobadas)

Notas mayores o iguales a 6: [ 8.5  6.   9.2  7.8 10. ]
